---
global:
  panel-background: "#303030"
  button-background-inactive: "#60202020"
  button-background-active: "#80101010"
  guide-color: "#ffffff"
  panel-max-levels: 2
  panel-radius: 200
  default-icon-style: square
  default-icon-text: "S"
  # The {{FILE}} placeholder will be replaced with a temporary .tex file to which the content is written.
  tex-editor:
    - bash
    - -c
    - konsole --geometry "800x400$(xdotool getmouselocation | sed -e 's/x:/+/;s/ y:/+/;s/ screen.*$//')" -e vim {{FILE}} +star
buttons:
  - slot: 0x00000100
    stroke: "#ffffff"
    stroke-width: 1
  - slot: 0x00000101
    stroke-width: 2
  - slot: 0x00000102
    stroke: "#330000"
  - slot: 0x00010100
    font-family: Times New Roman
  - slot: 0x00010101
    stroke-width: 2
    fill: "#0f0f0f"
    font-family: Cantarell
    stroke-opacity: 0.2
  - slot: 0x00010102
    stroke: "#ffc"
    stroke-dasharray: 2 1
    stroke-opacity: 0.8
    font-size: 10
    font-family: Linux Libertine
  - slot: 0x00010203
    stroke: "#ffc"
    stroke-dasharray: 2 1
    stroke-dashoffset: 1
    stroke-opacity: 0.8
    font-size: 10
    font-family: Linux Libertine
  - slot: 0x00020101
    fill: "#ff00f0"
    fill-opacity: 0.5
    stroke-opacity: 0.7
  - slot: 0x00020100
    fill: "#ff0000"
    fill-opacity: 0.5
  - slot: 0x00030100
    fill: "#fff000"
    fill-opacity: 0.9
  - slot: 0x00030101
    fill: "#0fff00"
    fill-opacity: 0.5
  - slot: 0x00030102
    fill: url(#grid-5x5-45)
    fill-opacity: 1.0
  - slot: 0x00040100
    marker-start: url(#dot)
    marker-end: none
  - slot: 0x00040101
    marker-start: none
    marker-end: url(#arrow-simple-forward)
  - slot: 0x00040102
    marker-start: url(#arrow-simple-reverse)
    marker-end: url(#arrow-simple-forward)
    fill: "#134729"
    fill-opacity: 0.8
  - slot: 0x00040200
    marker-start: url(#arrow-simple-reverse)
    marker-mid: url(#dot)
    marker-end: url(#arrow-simple-forward)
    fill: "#125df4"
    fill-opacity: 0.6
  - slot: 0x01000100
    stroke-width: 10
    fill-opacity: 0.4
  - slot: 0x01000101
    stroke-width: 20
    fill-opacity: 0.3
  - slot: 0x01000200
    stroke-linecap: round
  - slot: 0x01000201
    stroke-linejoin: round
  - slot: 0x01010200
    marker-start: url(#arrow-simple-reverse)
    marker-mid: url(#dot)
    marker-end: url(#arrow-simple-forward)
    stroke-linecap: round
  - slot: 0x01010201
    marker-start: url(#arrow-simple-reverse)
    marker-mid: url(#dot)
    marker-end: url(#arrow-simple-forward)
    stroke-linejoin: round
  - slot: 0x00040202
    icon: >
      <svg width="400" height="346" version="1.1" viewBox="0 0 400 346" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
      <g transform="matrix(.56578 0 0 .56578 205.89 242.34)" fill="#fff8e1" stroke-width="1.2726">
        <g transform="matrix(3.89,0,0,3.89,-175.05,-175.05)" fill="#fff8e1" stroke-linecap="round">
          <path d="m69.313 54.442c-0.397 0-0.798-0.118-1.147-0.363-0.904-0.636-1.122-1.883-0.487-2.786l10.118-14.399-10.118-14.399c-0.635-0.904-0.417-2.151 0.487-2.786 0.904-0.637 2.151-0.417 2.786 0.486l10.926 15.549c0.484 0.69 0.484 1.61 0 2.3l-10.926 15.548c-0.389 0.554-1.009 0.85-1.639 0.85z" />
          <path d="m57.693 30.092c1.104 0 2-0.896 2-2v-26.092c0-1.104-0.896-2-2-2h-47.934c-0.013 0-0.024 3e-3 -0.037 4e-3 -0.037 0-0.074 8e-3 -0.111 0.011-0.122 9e-3 -0.24 0.027-0.354 0.057-0.046 0.011-0.089 0.026-0.133 0.041-0.113 0.038-0.221 0.085-0.324 0.142-0.025 0.014-0.053 0.019-0.077 0.034-0.012 7e-3 -0.02 0.018-0.031 0.025-0.13 0.083-0.252 0.177-0.36 0.287-0.019 0.019-0.033 0.042-0.051 0.061-0.085 0.095-0.161 0.197-0.228 0.307-0.024 0.04-0.045 0.081-0.066 0.122-0.052 0.101-0.094 0.206-0.129 0.316-0.013 0.042-0.028 0.082-0.038 0.125-0.037 0.151-0.061 0.306-0.061 0.468v69.787c0 0.17 0.028 0.333 0.068 0.49 0.011 0.043 0.025 0.083 0.039 0.124 0.04 0.123 0.091 0.239 0.152 0.35 0.019 0.033 0.034 0.068 0.054 0.1 0.086 0.135 0.185 0.26 0.3 0.371 0.022 0.021 0.047 0.037 0.07 0.058 0.102 0.09 0.214 0.169 0.333 0.237 0.021 0.012 0.037 0.03 0.058 0.042l31.016 16.213c0.29 0.153 0.608 0.228 0.926 0.228 0.359 0 0.718-0.097 1.036-0.289 0.598-0.362 0.964-1.012 0.964-1.711v-14.213h14.918c1.104 0 2-0.896 2-2v-26.787c0-1.104-0.896-2-2-2s-2 0.896-2 2v24.787h-12.918v-51.574c0-0.745-0.414-1.428-1.074-1.772l-23.799-12.441h37.791v24.092c0 1.104 0.896 2 2 2z" />
          <path d="m80.241 38.894h-32.705c-1.104 0-2-0.896-2-2s0.896-2 2-2h32.705c1.104 0 2 0.896 2 2s-0.895 2-2 2z" />
        </g>
      </g>
      </svg>
svg-defs:
  - id: grid-5x5-45
    type: pattern
    attrs:
      width: 5
      height: 5
      patternTransform: rotate(45)
      patternUnits: userSpaceOnUse
    svg: >
      <line x1="2.5" y1="0" x2="2.5" y2="5" stroke="#000"/>
      <line x1="0" y1="2.5" x2="5" y2="2.5" stroke="#000"/>
  - id: dot
    type: marker
    attrs:
      viewBox: "0 0 10 10"
      refX: 5
      refY: 5
      markerWidth: 5
      markerHeight: 5
    svg: >
      <circle cx="5" cy="5" r="5" fill="red" />
  - id: arrow-simple-forward
    type: marker
    attrs:
      orient: 0
      viewBox: "0 0 3 5"
      refX: 2
      refY: 2.5
      markerWidth: 3
      markerHeight: 5
      overflow: visible
    svg: >
      <path d="M 0.5,0.4 C 1,1.4 1.6,2 2.4,2.5 C 1.6,3 1,3.6 0.5,4.6"
       style="fill:none;stroke:context-stroke;stroke-width:0.7;
      stroke-linecap:round;stroke-linejoin:round;
      stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"/>
  - id: arrow-simple-reverse
    type: marker
    attrs:
      orient: 180
      viewBox: "0 0 3 5"
      refX: 2
      refY: 2.5
      markerWidth: 3
      markerHeight: 5
      overflow: visible
    svg: >
      <path d="M 0.5,0.4 C 1,1.4 1.6,2 2.4,2.5 C 1.6,3 1,3.6 0.5,4.6"
       style="fill:none;stroke:context-stroke;stroke-width:0.7;
      stroke-linecap:round;stroke-linejoin:round;
      stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"/>
  - id: gradient-1
    type: gradient
    svg: ""
...
