---
global:
  panel-background: "#303030"
  button-background-inactive: "#60202020"
  button-background-active: "#80101010"
  guide-color: "#ffffff"
  panel-max-levels: 2
  panel-radius: 200
  default-icon-style: circle
  default-icon-text: "S"
buttons:
  - slot: 0x00000100
    stroke: "#ffffff"
    stroke-width: 1
  - slot: 0x00000101
    stroke-width: 2
  - slot: 0x00000102
    stroke: "#330000"
  - slot: 0x00010100
    font-family: Times New Roman
  - slot: 0x00010101
    stroke-width: 2
    fill: "#0f0f0f"
    font-family: Cantarell
    stroke-opacity: 0.2
  - slot: 0x00010102
    stroke: "#ffc"
    stroke-dasharray: 2 1
    stroke-opacity: 0.8
    font-size: 10
    font-family: Linux Libertine
  - slot: 0x00020101
    fill: "#ff00f0"
    fill-opacity: 0.5
    stroke-opacity: 0.7
  - slot: 0x00020100
    fill: "#ff0000"
    fill-opacity: 0.5
  - slot: 0x00030100
    fill: "#fff000"
    fill-opacity: 0.9
  - slot: 0x00030101
    fill: "#0fff00"
    fill-opacity: 0.5
  - slot: 0x00030102
    fill: url(#grid-5x5-45)
    fill-opacity: 1.0
  - slot: 0x00040100
    marker-start: url(#dot)
    marker-end: none
  - slot: 0x00040101
    marker-start: none
    marker-end: url(#arrow-simple-forward)
  - slot: 0x00040102
    marker-start: url(#arrow-simple-reverse)
    marker-end: url(#arrow-simple-forward)
    fill: "#134729"
    fill-opacity: 0.8
  - slot: 0x00050100
    svg: >
      <inkscape:clipboard style="fill:#314159"/>
  - slot: 0x01000100
    stroke-width: 10
    fill-opacity: 0.4
  - slot: 0x01000101
    stroke-width: 20
    fill-opacity: 0.3
svg-defs:
  - id: grid-5x5-45
    type: pattern
    attrs:
      width: 5
      height: 5
      patternTransform: rotate(45)
      patternUnits: userSpaceOnUse
    svg: >
      <line x1="2.5" y1="0" x2="2.5" y2="5" stroke="#000"/>
      <line x1="0" y1="2.5" x2="5" y2="2.5" stroke="#000"/>
  - id: dot
    type: marker
    attrs:
      viewBox: "0 0 10 10"
      refX: 5
      refY: 5
      markerWidth: 5
      markerHeight: 5
    svg: >
      <circle cx="5" cy="5" r="5" fill="red" />
  - id: arrow-simple-forward
    type: marker
    attrs:
      orient: 0
      viewBox: "0 0 3 5"
      refX: 2
      refY: 2.5
      markerWidth: 3
      markerHeight: 5
      overflow: visible
    svg: >
      <path d="M 0.5,0.4 C 1,1.4 1.6,2 2.4,2.5 C 1.6,3 1,3.6 0.5,4.6"
       style="fill:none;stroke:context-stroke;stroke-width:0.7;
      stroke-linecap:round;stroke-linejoin:round;
      stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"/>
  - id: arrow-simple-reverse
    type: marker
    attrs:
      orient: 180
      viewBox: "0 0 3 5"
      refX: 2
      refY: 2.5
      markerWidth: 3
      markerHeight: 5
      overflow: visible
    svg: >
      <path d="M 0.5,0.4 C 1,1.4 1.6,2 2.4,2.5 C 1.6,3 1,3.6 0.5,4.6"
       style="fill:none;stroke:context-stroke;stroke-width:0.7;
      stroke-linecap:round;stroke-linejoin:round;
      stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"/>
  - id: gradient-1
    type: gradient
    svg: ""
...
