---
global:
  panel-background: "#303030"
  button-background-inactive: "#80202020"
  button-background-active: "#90101010"
  guide-color: "#ffffff"
  panel-max-levels: 2
  panel-radius: 200
  default-icon-style: circle
  default-icon-text: "S"
buttons:
  - slot: 0x00000100
    stroke: "#ffffff"
    stroke-width: 1
  - slot: 0x00000101
    stroke-width: 2
  - slot: 0x00000102
    stroke: "#330000"
  - slot: 0x00010100
    font-family: Times New Roman
  - slot: 0x00010101
    stroke-width: 2
    fill: "#0f0f0f"
    font-family: Cantarell
    stroke-opacity: 0.2
  - slot: 0x00010102
    stroke: "#fff"
    stroke-opacity: 0.8
    font-size: 10
    font-family: Linux Libertine
  - slot: 0x00020101
    fill: "#ff00f0"
    fill-opacity: 0.5
    stroke-opacity: 0.7
  - slot: 0x00020100
    fill: "#ff0000"
    fill-opacity: 0.5
  - slot: 0x00030100
    fill: "#fff000"
    fill-opacity: 0.9
  - slot: 0x00030101
    fill: "#0fff00"
    fill-opacity: 0.5
  - slot: 0x00050100
    svg: |
      <?xml version="1.0" encoding="UTF-8" standalone="no"?>
      <svg><inkscape:clipboard style="{style_string}"/></svg>
  - slot: 0x01000100
    stroke-width: 10
  - slot: 0x01000101
    stroke-width: 20
...
