---
global:
  panel-background: 0x303030
  button-background: 0x20202020
  guide-color: 0xffffff
  panel-max-levels: 2
  panel-radius: 200
buttons:
  - slot: 0x00000100
    stroke: "#ffffff"
    stroke-width: 1
  - slot: 0x00000101
    stroke-width: 2
  - slot: 0x00000102
    stroke: "#330000"
  - slot: 0x00010100
    font: Times New Roman
  - slot: 0x00010101
    font: ET Book OT
  - slot: 0x00020100
    fill: "#ff0000"
    fill-opacity: 0.5
  - slot: 0x00030100
    fill: "#fff000"
    fill-opacity: 1.0
  - slot: 0x00030101
    fill: "#0fff00"
    fill-opacity: 0.5
  - slot: 0x00050100
    svg: |
      <?xml version="1.0" encoding="UTF-8" standalone="no"?>
      <svg><inkscape:clipboard style="{style_string}"/></svg>
  - slot: 0x01000100
    stroke-width: 10
  - slot: 0x01000101
    stroke-width: 20
...
